from __future__ import annotations

from PySide6.QtCore import QObject, Signal, QSettings


TRANSLATIONS = {
    "en": {
        "sidebar.tagline": "Lose Yourself in Sound", "sidebar.menu": "MENU", "sidebar.appearance": "APPEARANCE",
        "nav.home": "Home", "nav.discover": "Discover", "nav.library": "Library", "nav.favorites": "Favorites",
        "nav.playlists": "Playlists", "nav.assistant": "AI Assistant", "nav.ytbox": "YT BOX", "nav.settings": "Settings",
        "theme.dark": "Dark Mode", "theme.light": "Light Mode", "theme.on": "On", "theme.off": "Off",
        "language.title": "Language & Region", "language.subtitle": "Choose interface and regional preferences.",
        "language.interface": "Interface language", "language.desc": "Choose the language used by LYRx. More screens will join this global translation system as localization expands.",
        "language.region": "Region", "language.region_desc": "Saved locally for future regional recommendations, content and account preferences.",
        "language.status": "Interface language: {language}",
    },
    "hi": {
        "sidebar.tagline": "संगीत में खो जाइए", "sidebar.menu": "मेन्यू", "sidebar.appearance": "रूप-रंग",
        "nav.home": "होम", "nav.discover": "खोजें", "nav.library": "लाइब्रेरी", "nav.favorites": "पसंदीदा",
        "nav.playlists": "प्लेलिस्ट", "nav.assistant": "AI सहायक", "nav.ytbox": "YT BOX", "nav.settings": "सेटिंग्स",
        "theme.dark": "डार्क मोड", "theme.light": "लाइट मोड", "theme.on": "चालू", "theme.off": "बंद",
        "language.title": "भाषा और क्षेत्र", "language.subtitle": "इंटरफ़ेस की भाषा और क्षेत्रीय प्राथमिकताएँ चुनें।",
        "language.interface": "इंटरफ़ेस भाषा", "language.desc": "LYRx में उपयोग होने वाली भाषा चुनें। लोकलाइज़ेशन बढ़ने के साथ और स्क्रीन इस वैश्विक अनुवाद प्रणाली से जुड़ेंगी।",
        "language.region": "क्षेत्र", "language.region_desc": "भविष्य की क्षेत्रीय सिफारिशों, सामग्री और अकाउंट प्राथमिकताओं के लिए स्थानीय रूप से सहेजा जाता है।",
        "language.status": "इंटरफ़ेस भाषा: {language}",
    },
    "fr": {
        "sidebar.tagline": "Perdez-vous dans le son", "sidebar.menu": "MENU", "sidebar.appearance": "APPARENCE",
        "nav.home": "Accueil", "nav.discover": "Découvrir", "nav.library": "Bibliothèque", "nav.favorites": "Favoris",
        "nav.playlists": "Playlists", "nav.assistant": "Assistant IA", "nav.ytbox": "YT BOX", "nav.settings": "Paramètres",
        "theme.dark": "Mode sombre", "theme.light": "Mode clair", "theme.on": "Activé", "theme.off": "Désactivé",
        "language.title": "Langue et région", "language.subtitle": "Choisissez la langue de l’interface et vos préférences régionales.",
        "language.interface": "Langue de l’interface", "language.desc": "Choisissez la langue utilisée par LYRx. D’autres écrans rejoindront ce système global à mesure que la localisation s’étendra.",
        "language.region": "Région", "language.region_desc": "Enregistrée localement pour les futures recommandations régionales, le contenu et les préférences du compte.",
        "language.status": "Langue de l’interface : {language}",
    },
}


# Day 27 Phase 1.2: literal UI translations used by existing Settings widgets.
# This lets the current Settings architecture localize live without rewriting
# every widget constructor. Unknown text safely stays in English.
LITERAL_TRANSLATIONS = {
    "hi": {
        '♫  Local Audio  •  Offline': '♫  लोकल ऑडियो  •  ऑफ़लाइन',

        'NOW PLAYING': 'अभी चल रहा है',
        '●  LIVE': '●  लाइव',
        '♫  Online Audio': '♫  ऑनलाइन ऑडियो',
        'Shuffle': 'शफ़ल',
        'Previous': 'पिछला',
        'Play': 'चलाएँ',
        'Pause': 'रोकें',
        'Next': 'अगला',
        'Repeat': 'दोहराएँ',
        '☷  Queue': '☷  कतार',
        '♫  Playlist': '♫  प्लेलिस्ट',
        '↗  Share': '↗  साझा करें',
        '•••': '•••',
        '☷  NEXT UP': '☷  अगला',
        '0 songs': '0 गाने',
        '1 song': '1 गाना',
        'songs': 'गाने',

        'Nothing Playing': 'कुछ भी नहीं चल रहा',
        'Select a song to start listening': 'सुनना शुरू करने के लिए कोई गाना चुनें',
        'Continue Listening': 'सुनना जारी रखें',
        'More  ›': 'और  ›',
        'Playlists for You': 'आपके लिए प्लेलिस्ट',
        'View All  ›': 'सभी देखें  ›',
        '🎵  No music found': '🎵  कोई संगीत नहीं मिला',
        'Clear  ×': 'साफ़ करें  ×',
        'Search Results': 'खोज परिणाम',
        'Search songs, artists or music online...': 'गाने, कलाकार या संगीत ऑनलाइन खोजें...',
        'YOUR SOUND • YOUR MOMENT': 'आपकी धुन • आपका पल',
        'What do you want\nto hear today?': 'आज आप क्या\nसुनना चाहते हैं?',
        'Find Your Frequency  ✦': 'अपनी धुन खोजें  ✦',
        'Discover your soul,\nMillions of beats, one experience.': 'अपनी रूह की धुन खोजें,\nलाखों बीट्स, एक अनुभव।',
        'Explore Music  →': 'संगीत खोजें  →',
        'Open Library': 'लाइब्रेरी खोलें',
        'Your Vibe': 'आपका मूड',
        'See All  →': 'सभी देखें  →',
        'Chill': 'चिल',
        'Relax & unwind': 'आराम करें',
        'Focus': 'फोकस',
        'Stay productive': 'ध्यान बनाए रखें',
        'Happy': 'खुश',
        'Good vibes': 'अच्छी वाइब्स',
        'Workout': 'वर्कआउट',
        'Power up': 'ऊर्जा बढ़ाएँ',
        'Sleep': 'नींद',
        'Drift away': 'आराम से सोएँ',
        'Rainy Day': 'बारिश का दिन',
        'Cozy moments': 'सुकून भरे पल',
        'Discover': 'खोजें',
        'Explore new sounds, moods and music.': 'नई धुनें, मूड और संगीत खोजें।',
        'Find Your Next Favorite': 'अपना अगला पसंदीदा गीत खोजें',
        "Discover music through LYRx's multi-provider online catalog.": 'LYRx के मल्टी-प्रोवाइडर ऑनलाइन कैटलॉग से संगीत खोजें।',
        'Trending Now': 'अभी ट्रेंडिंग',
        'Online  ●': 'ऑनलाइन  ●',
        'Connecting to LYRx online music...': 'LYRx ऑनलाइन संगीत से कनेक्ट हो रहा है...',
        'Browse by Mood': 'मूड के अनुसार खोजें',
        'Choose a mood  ›': 'मूड चुनें  ›',
        'Explore Genres': 'जॉनर खोजें',
        'Choose a genre  ›': 'जॉनर चुनें  ›',
        'LYRx multi-provider music discovery ✦': 'LYRx मल्टी-प्रोवाइडर संगीत खोज ✦',
        'Popular Now': 'अभी लोकप्रिय',
        'Loading music...': 'संगीत लोड हो रहा है...',
        'Your Library': 'आपकी लाइब्रेरी',
        'Everything you love, all in one place.': 'आपका पसंदीदा संगीत, एक ही जगह।',
        '0 songs': '0 गाने',
        'Your music. Your collection.': 'आपका संगीत। आपका कलेक्शन।',
        'Pick a track and let LYRx take care of the rest.': 'एक ट्रैक चुनें और बाकी LYRx पर छोड़ दें।',
        'Search your library...': 'अपनी लाइब्रेरी में खोजें...',
        'All Songs': 'सभी गाने',
        'No songs found in your library.': 'आपकी लाइब्रेरी में कोई गाना नहीं मिला।',
        'Favorites': 'पसंदीदा',
        'Your favorite songs, all in one place.': 'आपके पसंदीदा गाने, एक ही जगह।',
        'No favorites yet': 'अभी कोई पसंदीदा नहीं',
        'Songs you favorite will appear here.': 'आपके पसंद किए गए गाने यहाँ दिखाई देंगे।',
        '▶  Play': '▶  चलाएँ',
        'Your Playlists': 'आपकी प्लेलिस्ट',
        'Create, organize and enjoy your music.': 'अपना संगीत बनाएँ, व्यवस्थित करें और आनंद लें।',
        '＋  New Playlist': '＋  नई प्लेलिस्ट',
        'Search your playlists...': 'अपनी प्लेलिस्ट खोजें...',
        '♫  No playlists found': '♫  कोई प्लेलिस्ट नहीं मिली',
        'Create Playlist': 'प्लेलिस्ट बनाएँ',
        'Create New Playlist': 'नई प्लेलिस्ट बनाएँ',
        'Give your playlist a name and description.': 'अपनी प्लेलिस्ट को नाम और विवरण दें।',
        'Playlist name': 'प्लेलिस्ट का नाम',
        'Description (optional)': 'विवरण (वैकल्पिक)',
        'Cancel': 'रद्द करें',
        'Delete playlist': 'प्लेलिस्ट हटाएँ',
        '←  Back': '←  वापस',
        '▶  Play Playlist': '▶  प्लेलिस्ट चलाएँ',
        'Songs in this playlist': 'इस प्लेलिस्ट के गाने',
        'LYRx AI Assistant': 'LYRx AI सहायक',
        'Your personal music companion.': 'आपका निजी संगीत साथी।',
        'Clear Chat': 'चैट साफ़ करें',
        '●  Ready': '●  तैयार',
        'Ask LYRx anything about music...': 'LYRx से संगीत के बारे में कुछ भी पूछें...',
        'Send  ➤': 'भेजें  ➤',
        '🎵  Recommend songs': '🎵  गाने सुझाएँ',
        '🎧  Make a playlist': '🎧  प्लेलिस्ट बनाएँ',
        '💜  My mood': '💜  मेरा मूड',
        '🔥  What should I play?': '🔥  क्या चलाऊँ?',
        'Search music and videos across YouTube.': 'YouTube पर संगीत और वीडियो खोजें।',
        'Find Your Music': 'अपना संगीत खोजें',
        'Search by song, artist, album, live performance or music video.': 'गाना, कलाकार, एल्बम, लाइव परफॉर्मेंस या म्यूजिक वीडियो खोजें।',
        'Search YouTube...': 'YouTube पर खोजें...',
        'Search': 'खोजें',
        'Discover on YouTube': 'YouTube पर खोजें',
        'Search the YouTube catalog': 'YouTube कैटलॉग खोजें',
        'Try searching for an artist or song.': 'किसी कलाकार या गाने को खोजकर देखें।',
        'Add to Favorites': 'पसंदीदा में जोड़ें',
        'Add to Playlist': 'प्लेलिस्ट में जोड़ें',
        'Welcome to LYRx': 'LYRx में आपका स्वागत है',
        'Sign in to your LYRx account': 'अपने LYRx अकाउंट में साइन इन करें',
        'Email Login': 'ईमेल लॉगिन',
        'Create Account': 'अकाउंट बनाएँ',
        'or continue with': 'या इसके साथ जारी रखें',
        'Sign Out': 'साइन आउट',
        'Remember me': 'मुझे याद रखें',
        'Forgot password?': 'पासवर्ड भूल गए?',
        'Sign In  →': 'साइन इन  →',
        'Phone verification': 'फ़ोन सत्यापन',
        'Send OTP': 'OTP भेजें',
        'Verify OTP': 'OTP सत्यापित करें',
        'Display name': 'डिस्प्ले नाम',
        'Create password': 'पासवर्ड बनाएँ',
        'Confirm password': 'पासवर्ड की पुष्टि करें',

        "Settings": "सेटिंग्स",
        "Manage your LYRx experience.": "अपने LYRx अनुभव को प्रबंधित करें।",
        "PREFERENCES": "प्राथमिकताएँ",
        "Appearance": "रूप-रंग",
        "Theme, layout and visual preferences.": "थीम, लेआउट और दृश्य प्राथमिकताएँ।",
        "Playback": "प्लेबैक",
        "Autoplay, volume and crossfade controls.": "ऑटोप्ले, वॉल्यूम और क्रॉसफेड नियंत्रण।",
        "Audio Quality": "ऑडियो गुणवत्ता",
        "Streaming quality and data usage.": "स्ट्रीमिंग गुणवत्ता और डेटा उपयोग।",
        "Downloads & Storage": "डाउनलोड और स्टोरेज",
        "Download location and cache management.": "डाउनलोड स्थान और कैश प्रबंधन।",
        "Privacy & Security": "गोपनीयता और सुरक्षा",
        "Private listening and authentication.": "निजी सुनना और प्रमाणीकरण।",
        "Notifications": "सूचनाएँ",
        "Music and application alerts.": "संगीत और ऐप सूचनाएँ।",
        "Language & Region": "भाषा और क्षेत्र",
        "Language and regional preferences.": "भाषा और क्षेत्रीय प्राथमिकताएँ।",
        "Accessibility": "सुगम्यता",
        "Motion and text accessibility.": "मोशन और टेक्स्ट सुगम्यता।",
        "About LYRx": "LYRx के बारे में",
        "Version and project information.": "संस्करण और प्रोजेक्ट की जानकारी।",
        "Profile & Account": "प्रोफ़ाइल और अकाउंट",
        "Manage your LYRx identity and account information.": "अपनी LYRx पहचान और अकाउंट जानकारी प्रबंधित करें।",
        "Personal information": "व्यक्तिगत जानकारी",
        "First name": "पहला नाम",
        "Your first name shown across LYRx.": "LYRx में दिखाया जाने वाला आपका पहला नाम।",
        "Last name": "अंतिम नाम",
        "Your surname or family name.": "आपका उपनाम या पारिवारिक नाम।",
        "Date of birth": "जन्म तिथि",
        "Used only as part of your local LYRx profile.": "केवल आपकी स्थानीय LYRx प्रोफ़ाइल के लिए उपयोग किया जाता है।",
        "Gender": "लिंग",
        "Optional profile information.": "वैकल्पिक प्रोफ़ाइल जानकारी।",
        "Account information": "अकाउंट जानकारी",
        "Email address": "ईमेल पता",
        "Email linked to your Firebase account.": "आपके Firebase अकाउंट से जुड़ा ईमेल।",
        "Phone number": "फ़ोन नंबर",
        "Phone number linked through Firebase Phone OTP.": "Firebase Phone OTP से जुड़ा फ़ोन नंबर।",
        "Authentication": "प्रमाणीकरण",
        "Manage Firebase email/password, Google Sign-In and Phone OTP access.": "Firebase ईमेल/पासवर्ड, Google Sign-In और Phone OTP एक्सेस प्रबंधित करें।",
        "Change Photo": "फ़ोटो बदलें",
        "Remove Photo": "फ़ोटो हटाएँ",
        "Save Changes": "बदलाव सहेजें",
        "Manage Account": "अकाउंट प्रबंधित करें",
        "Personalize how LYRx looks on your desktop.": "अपने डेस्कटॉप पर LYRx का रूप अपनी पसंद के अनुसार बदलें।",
        "Dark mode": "डार्क मोड",
        "Use the signature LYRx dark-purple interface.": "LYRx का खास डार्क-पर्पल इंटरफ़ेस उपयोग करें।",
        "Compact layout": "कॉम्पैक्ट लेआउट",
        "Reduce spacing for a denser desktop layout.": "अधिक कॉम्पैक्ट लेआउट के लिए स्पेसिंग कम करें।",
        "Choose how music behaves during listening sessions.": "सुनते समय संगीत का व्यवहार चुनें।",
        "Autoplay": "ऑटोप्ले",
        "Continue playing related music when your queue ends.": "क्यू समाप्त होने पर संबंधित संगीत चलाते रहें।",
        "Gapless playback": "गैपलेस प्लेबैक",
        "Reduce silence between compatible tracks.": "अनुकूल ट्रैक्स के बीच की खामोशी कम करें।",
        "Normalize volume": "वॉल्यूम सामान्य करें",
        "Keep playback levels more consistent between songs.": "गानों के बीच प्लेबैक स्तर अधिक समान रखें।",
        "Crossfade": "क्रॉसफेड",
        "Blend the end of one track into the next.": "एक ट्रैक के अंत को अगले ट्रैक की शुरुआत से मिलाएँ।",
        "Control provider-aware streaming preferences and network usage.": "प्रोवाइडर-अनुकूल स्ट्रीमिंग और नेटवर्क उपयोग नियंत्रित करें।",
        "Streaming quality": "स्ट्रीमिंग गुणवत्ता",
        "Data saver": "डेटा सेवर",
        "Prefer preview / lower-bandwidth playable sources when available and skip non-essential online artwork downloads.": "उपलब्ध होने पर कम-बैंडविड्थ स्रोत चुनें और गैर-ज़रूरी ऑनलाइन आर्टवर्क डाउनलोड छोड़ें।",
        "Effective network mode": "प्रभावी नेटवर्क मोड",
        "Shows how LYRx will currently handle online playback requests.": "दिखाता है कि LYRx अभी ऑनलाइन प्लेबैक अनुरोध कैसे संभालेगा।",
        "Manage future offline content and LYRx temporary files.": "भविष्य की ऑफ़लाइन सामग्री और LYRx की अस्थायी फ़ाइलें प्रबंधित करें।",
        "Download location": "डाउनलोड स्थान",
        "Folder reserved for future offline downloads and exported LYRx content.": "भविष्य के ऑफ़लाइन डाउनलोड और एक्सपोर्टेड LYRx सामग्री के लिए फ़ोल्डर।",
        "Offline Downloads": "ऑफ़लाइन डाउनलोड",
        "Download music for offline listening when supported by your LYRx plan and licensed music catalog.": "जब आपके LYRx प्लान और लाइसेंस प्राप्त संगीत कैटलॉग में उपलब्ध हो, तब ऑफ़लाइन सुनने के लिए संगीत डाउनलोड करें।",
        "COMING SOON": "जल्द आ रहा है",
        "Application cache": "ऐप कैश",
        "Temporary LYRx files stored in your user cache directory. Clearing them does not remove your profile or playlists.": "आपकी यूज़र कैश डायरेक्टरी में रखी अस्थायी LYRx फ़ाइलें। इन्हें साफ़ करने से प्रोफ़ाइल या प्लेलिस्ट नहीं हटती।",
        "Open": "खोलें",
        "Change": "बदलें",
        "Clear Cache": "कैश साफ़ करें",
        "Control private listening and account security.": "निजी सुनने और अकाउंट सुरक्षा को नियंत्रित करें।",
        "Private listening session": "निजी सुनने का सत्र",
        "Keep the current session private from future LYRx recommendation/history signals.": "वर्तमान सत्र को भविष्य की LYRx सिफारिश/इतिहास संकेतों से निजी रखें।",
        "Security": "सुरक्षा",
        "Account Security": "अकाउंट सुरक्षा",
        "Manage Email, Google and Phone OTP authentication.": "ईमेल, Google और Phone OTP प्रमाणीकरण प्रबंधित करें।",
        "Privacy": "गोपनीयता",
        "Privacy Policy": "गोपनीयता नीति",
        "Read how the LYRx portfolio build handles account information.": "जानें कि LYRx पोर्टफोलियो बिल्ड अकाउंट जानकारी कैसे संभालता है।",
        "Open Privacy Policy": "गोपनीयता नीति खोलें",
        "Choose which LYRx desktop alerts you want to receive.": "चुनें कि आप कौन-सी LYRx डेस्कटॉप सूचनाएँ पाना चाहते हैं।",
        "Music recommendations": "संगीत सुझाव",
        "Allow future discovery and recommendation notifications when those services are active.": "सेवाएँ सक्रिय होने पर भविष्य की डिस्कवरी और सुझाव सूचनाएँ अनुमति दें।",
        "Application updates": "ऐप अपडेट",
        "Receive LYRx feature and application update notices.": "LYRx फीचर और ऐप अपडेट की सूचनाएँ प्राप्त करें।",
        "Test desktop notification": "डेस्कटॉप सूचना जाँचें",
        "Send one Windows notification so you can verify that desktop alerts are available.": "डेस्कटॉप सूचनाएँ उपलब्ध हैं या नहीं जाँचने के लिए एक Windows सूचना भेजें।",
        "Send Test Notification": "टेस्ट सूचना भेजें",
        "Make LYRx more comfortable to use.": "LYRx को उपयोग में अधिक सुविधाजनक बनाएँ।",
        "Reduce motion": "मोशन कम करें",
        "Disable animated movement in supported LYRx controls, including Settings toggles.": "Settings टॉगल सहित समर्थित LYRx नियंत्रणों में एनीमेशन कम करें।",
        "Larger text": "बड़ा टेक्स्ट",
        "Increase text size across the Settings experience for easier reading.": "आसान पढ़ने के लिए Settings में टेक्स्ट का आकार बढ़ाएँ।",
        "Project information, links and current build details.": "प्रोजेक्ट जानकारी, लिंक और वर्तमान बिल्ड विवरण।",
        "Version": "संस्करण",
        "Current LYRx desktop portfolio build.": "वर्तमान LYRx डेस्कटॉप पोर्टफोलियो बिल्ड।",
        "Technology": "तकनीक",
        "Core technologies used by the current build.": "वर्तमान बिल्ड में उपयोग की गई मुख्य तकनीकें।",
        "Project status": "प्रोजेक्ट स्थिति",
        "LYRx is an independently developed portfolio project.": "LYRx स्वतंत्र रूप से विकसित पोर्टफोलियो प्रोजेक्ट है।",
        "LYRx website": "LYRx वेबसाइट",
        "Open the public LYRx project website.": "सार्वजनिक LYRx प्रोजेक्ट वेबसाइट खोलें।",
        "Open Website": "वेबसाइट खोलें",
        "View the public LYRx Privacy Policy.": "सार्वजनिक LYRx गोपनीयता नीति देखें।",
        "Terms": "शर्तें",
        "Terms of Service": "सेवा की शर्तें",
        "View the public LYRx Terms of Service.": "सार्वजनिक LYRx सेवा शर्तें देखें।",
        "←  Settings": "←  सेटिंग्स",
        "Automatic": "स्वचालित", "Low": "कम", "Normal": "सामान्य", "High": "उच्च", "Very High": "बहुत उच्च",
        "Default": "डिफ़ॉल्ट", "Female": "महिला", "Male": "पुरुष", "Non-binary": "नॉन-बाइनरी", "Prefer not to say": "बताना नहीं चाहते",
        "India": "भारत", "United States": "संयुक्त राज्य", "Canada": "कनाडा", "United Kingdom": "यूनाइटेड किंगडम", "Australia": "ऑस्ट्रेलिया", "Other": "अन्य",
    },
    "fr": {
        '♫  Local Audio  •  Offline': '♫  Audio local  •  Hors ligne',

        'NOW PLAYING': 'LECTURE EN COURS',
        '●  LIVE': '●  EN DIRECT',
        '♫  Online Audio': '♫  Audio en ligne',
        'Shuffle': 'Aléatoire',
        'Previous': 'Précédent',
        'Play': 'Lecture',
        'Pause': 'Pause',
        'Next': 'Suivant',
        'Repeat': 'Répéter',
        '☷  Queue': '☷  File',
        '♫  Playlist': '♫  Playlist',
        '↗  Share': '↗  Partager',
        '•••': '•••',
        '☷  NEXT UP': '☷  À SUIVRE',
        '0 songs': '0 morceau',
        '1 song': '1 morceau',
        'songs': 'morceaux',

        'Nothing Playing': 'Aucune lecture',
        'Select a song to start listening': 'Sélectionnez un morceau pour commencer',
        'Continue Listening': 'Continuer l’écoute',
        'More  ›': 'Plus  ›',
        'Playlists for You': 'Playlists pour vous',
        'View All  ›': 'Tout voir  ›',
        '🎵  No music found': '🎵  Aucune musique trouvée',
        'Clear  ×': 'Effacer  ×',
        'Search Results': 'Résultats de recherche',
        'Search songs, artists or music online...': 'Rechercher des morceaux, artistes ou musique en ligne...',
        'YOUR SOUND • YOUR MOMENT': 'VOTRE SON • VOTRE MOMENT',
        'What do you want\nto hear today?': 'Qu’avez-vous envie\nd’écouter aujourd’hui ?',
        'Find Your Frequency  ✦': 'Trouvez votre fréquence  ✦',
        'Discover your soul,\nMillions of beats, one experience.': 'Découvrez votre univers,\ndes millions de rythmes, une expérience.',
        'Explore Music  →': 'Explorer la musique  →',
        'Open Library': 'Ouvrir la bibliothèque',
        'Your Vibe': 'Votre ambiance',
        'See All  →': 'Tout voir  →',
        'Chill': 'Détente',
        'Relax & unwind': 'Relaxez-vous',
        'Focus': 'Concentration',
        'Stay productive': 'Restez productif',
        'Happy': 'Heureux',
        'Good vibes': 'Bonnes ondes',
        'Workout': 'Entraînement',
        'Power up': 'Faites le plein d’énergie',
        'Sleep': 'Sommeil',
        'Drift away': 'Laissez-vous aller',
        'Rainy Day': 'Jour de pluie',
        'Cozy moments': 'Moments douillets',
        'Discover': 'Découvrir',
        'Explore new sounds, moods and music.': 'Explorez de nouveaux sons, ambiances et musiques.',
        'Find Your Next Favorite': 'Trouvez votre prochain favori',
        "Discover music through LYRx's multi-provider online catalog.": 'Découvrez la musique via le catalogue en ligne multi-fournisseurs de LYRx.',
        'Trending Now': 'Tendances actuelles',
        'Online  ●': 'En ligne  ●',
        'Connecting to LYRx online music...': 'Connexion à la musique en ligne LYRx...',
        'Browse by Mood': 'Parcourir par ambiance',
        'Choose a mood  ›': 'Choisir une ambiance  ›',
        'Explore Genres': 'Explorer les genres',
        'Choose a genre  ›': 'Choisir un genre  ›',
        'LYRx multi-provider music discovery ✦': 'Découverte musicale multi-fournisseurs LYRx ✦',
        'Popular Now': 'Populaire maintenant',
        'Loading music...': 'Chargement de la musique...',
        'Your Library': 'Votre bibliothèque',
        'Everything you love, all in one place.': 'Tout ce que vous aimez, au même endroit.',
        '0 songs': '0 morceau',
        'Your music. Your collection.': 'Votre musique. Votre collection.',
        'Pick a track and let LYRx take care of the rest.': 'Choisissez un morceau et laissez LYRx faire le reste.',
        'Search your library...': 'Rechercher dans votre bibliothèque...',
        'All Songs': 'Tous les morceaux',
        'No songs found in your library.': 'Aucun morceau trouvé dans votre bibliothèque.',
        'Favorites': 'Favoris',
        'Your favorite songs, all in one place.': 'Vos morceaux favoris, au même endroit.',
        'No favorites yet': 'Aucun favori pour le moment',
        'Songs you favorite will appear here.': 'Les morceaux ajoutés aux favoris apparaîtront ici.',
        '▶  Play': '▶  Lire',
        'Your Playlists': 'Vos playlists',
        'Create, organize and enjoy your music.': 'Créez, organisez et profitez de votre musique.',
        '＋  New Playlist': '＋  Nouvelle playlist',
        'Search your playlists...': 'Rechercher vos playlists...',
        '♫  No playlists found': '♫  Aucune playlist trouvée',
        'Create Playlist': 'Créer une playlist',
        'Create New Playlist': 'Créer une nouvelle playlist',
        'Give your playlist a name and description.': 'Donnez un nom et une description à votre playlist.',
        'Playlist name': 'Nom de la playlist',
        'Description (optional)': 'Description (facultative)',
        'Cancel': 'Annuler',
        'Delete playlist': 'Supprimer la playlist',
        '←  Back': '←  Retour',
        '▶  Play Playlist': '▶  Lire la playlist',
        'Songs in this playlist': 'Morceaux de cette playlist',
        'LYRx AI Assistant': 'Assistant IA LYRx',
        'Your personal music companion.': 'Votre compagnon musical personnel.',
        'Clear Chat': 'Effacer le chat',
        '●  Ready': '●  Prêt',
        'Ask LYRx anything about music...': 'Demandez à LYRx tout ce qui concerne la musique...',
        'Send  ➤': 'Envoyer  ➤',
        '🎵  Recommend songs': '🎵  Recommander des morceaux',
        '🎧  Make a playlist': '🎧  Créer une playlist',
        '💜  My mood': '💜  Mon humeur',
        '🔥  What should I play?': '🔥  Que dois-je écouter ?',
        'Search music and videos across YouTube.': 'Recherchez de la musique et des vidéos sur YouTube.',
        'Find Your Music': 'Trouvez votre musique',
        'Search by song, artist, album, live performance or music video.': 'Recherchez par morceau, artiste, album, concert ou clip.',
        'Search YouTube...': 'Rechercher sur YouTube...',
        'Search': 'Rechercher',
        'Discover on YouTube': 'Découvrir sur YouTube',
        'Search the YouTube catalog': 'Rechercher dans le catalogue YouTube',
        'Try searching for an artist or song.': 'Essayez de rechercher un artiste ou un morceau.',
        'Add to Favorites': 'Ajouter aux favoris',
        'Add to Playlist': 'Ajouter à une playlist',
        'Welcome to LYRx': 'Bienvenue sur LYRx',
        'Sign in to your LYRx account': 'Connectez-vous à votre compte LYRx',
        'Email Login': 'Connexion e-mail',
        'Create Account': 'Créer un compte',
        'or continue with': 'ou continuer avec',
        'Sign Out': 'Se déconnecter',
        'Remember me': 'Se souvenir de moi',
        'Forgot password?': 'Mot de passe oublié ?',
        'Sign In  →': 'Se connecter  →',
        'Phone verification': 'Vérification du téléphone',
        'Send OTP': 'Envoyer l’OTP',
        'Verify OTP': 'Vérifier l’OTP',
        'Display name': 'Nom affiché',
        'Create password': 'Créer un mot de passe',
        'Confirm password': 'Confirmer le mot de passe',

        "Settings": "Paramètres",
        "Manage your LYRx experience.": "Gérez votre expérience LYRx.",
        "PREFERENCES": "PRÉFÉRENCES",
        "Appearance": "Apparence",
        "Theme, layout and visual preferences.": "Thème, disposition et préférences visuelles.",
        "Playback": "Lecture",
        "Autoplay, volume and crossfade controls.": "Lecture automatique, volume et fondu enchaîné.",
        "Audio Quality": "Qualité audio",
        "Streaming quality and data usage.": "Qualité du streaming et utilisation des données.",
        "Downloads & Storage": "Téléchargements et stockage",
        "Download location and cache management.": "Emplacement des téléchargements et gestion du cache.",
        "Privacy & Security": "Confidentialité et sécurité",
        "Private listening and authentication.": "Écoute privée et authentification.",
        "Notifications": "Notifications",
        "Music and application alerts.": "Alertes musicales et de l’application.",
        "Language & Region": "Langue et région",
        "Language and regional preferences.": "Langue et préférences régionales.",
        "Accessibility": "Accessibilité",
        "Motion and text accessibility.": "Accessibilité des animations et du texte.",
        "About LYRx": "À propos de LYRx",
        "Version and project information.": "Version et informations sur le projet.",
        "Profile & Account": "Profil et compte",
        "Manage your LYRx identity and account information.": "Gérez votre identité LYRx et les informations de votre compte.",
        "Personal information": "Informations personnelles",
        "First name": "Prénom", "Your first name shown across LYRx.": "Votre prénom affiché dans LYRx.",
        "Last name": "Nom", "Your surname or family name.": "Votre nom de famille.",
        "Date of birth": "Date de naissance", "Used only as part of your local LYRx profile.": "Utilisée uniquement dans votre profil LYRx local.",
        "Gender": "Genre", "Optional profile information.": "Information de profil facultative.",
        "Account information": "Informations du compte",
        "Email address": "Adresse e-mail", "Email linked to your Firebase account.": "E-mail lié à votre compte Firebase.",
        "Phone number": "Numéro de téléphone", "Phone number linked through Firebase Phone OTP.": "Numéro lié via Firebase Phone OTP.",
        "Authentication": "Authentification", "Manage Firebase email/password, Google Sign-In and Phone OTP access.": "Gérez l’e-mail/mot de passe Firebase, Google Sign-In et Phone OTP.",
        "Change Photo": "Changer la photo", "Remove Photo": "Supprimer la photo", "Save Changes": "Enregistrer", "Manage Account": "Gérer le compte",
        "Personalize how LYRx looks on your desktop.": "Personnalisez l’apparence de LYRx sur votre ordinateur.",
        "Dark mode": "Mode sombre", "Use the signature LYRx dark-purple interface.": "Utilisez l’interface violet foncé emblématique de LYRx.",
        "Compact layout": "Disposition compacte", "Reduce spacing for a denser desktop layout.": "Réduisez les espacements pour une interface plus compacte.",
        "Choose how music behaves during listening sessions.": "Choisissez le comportement de la musique pendant l’écoute.",
        "Autoplay": "Lecture automatique", "Continue playing related music when your queue ends.": "Continuez avec de la musique associée à la fin de la file.",
        "Gapless playback": "Lecture sans interruption", "Reduce silence between compatible tracks.": "Réduisez le silence entre les morceaux compatibles.",
        "Normalize volume": "Normaliser le volume", "Keep playback levels more consistent between songs.": "Uniformisez davantage le niveau sonore entre les morceaux.",
        "Crossfade": "Fondu enchaîné", "Blend the end of one track into the next.": "Mélangez la fin d’un morceau avec le suivant.",
        "Control provider-aware streaming preferences and network usage.": "Contrôlez le streaming selon le fournisseur et l’utilisation du réseau.",
        "Streaming quality": "Qualité du streaming", "Data saver": "Économiseur de données",
        "Prefer preview / lower-bandwidth playable sources when available and skip non-essential online artwork downloads.": "Privilégiez les sources à faible bande passante et évitez les illustrations en ligne non essentielles.",
        "Effective network mode": "Mode réseau effectif", "Shows how LYRx will currently handle online playback requests.": "Indique comment LYRx gère actuellement la lecture en ligne.",
        "Manage future offline content and LYRx temporary files.": "Gérez le futur contenu hors ligne et les fichiers temporaires LYRx.",
        "Download location": "Emplacement des téléchargements", "Folder reserved for future offline downloads and exported LYRx content.": "Dossier réservé aux futurs téléchargements hors ligne et contenus exportés.",
        "Offline Downloads": "Téléchargements hors ligne", "Download music for offline listening when supported by your LYRx plan and licensed music catalog.": "Téléchargez de la musique pour l’écoute hors ligne lorsque votre offre LYRx et le catalogue sous licence le permettent.",
        "COMING SOON": "BIENTÔT",
        "Application cache": "Cache de l’application", "Temporary LYRx files stored in your user cache directory. Clearing them does not remove your profile or playlists.": "Fichiers LYRx temporaires stockés dans votre cache utilisateur. Leur suppression n’efface ni votre profil ni vos playlists.",
        "Open": "Ouvrir", "Change": "Modifier", "Clear Cache": "Vider le cache",
        "Control private listening and account security.": "Contrôlez l’écoute privée et la sécurité du compte.",
        "Private listening session": "Session d’écoute privée", "Keep the current session private from future LYRx recommendation/history signals.": "Gardez cette session privée pour les futurs signaux de recommandation et d’historique LYRx.",
        "Security": "Sécurité", "Account Security": "Sécurité du compte", "Manage Email, Google and Phone OTP authentication.": "Gérez l’authentification par e-mail, Google et Phone OTP.",
        "Privacy": "Confidentialité", "Privacy Policy": "Politique de confidentialité", "Read how the LYRx portfolio build handles account information.": "Découvrez comment LYRx gère les informations du compte.",
        "Open Privacy Policy": "Ouvrir la politique de confidentialité",
        "Choose which LYRx desktop alerts you want to receive.": "Choisissez les alertes LYRx que vous souhaitez recevoir.",
        "Music recommendations": "Recommandations musicales", "Allow future discovery and recommendation notifications when those services are active.": "Autorisez les futures notifications de découverte et de recommandation lorsque ces services sont actifs.",
        "Application updates": "Mises à jour de l’application", "Receive LYRx feature and application update notices.": "Recevez les annonces de fonctionnalités et mises à jour LYRx.",
        "Test desktop notification": "Tester la notification", "Send one Windows notification so you can verify that desktop alerts are available.": "Envoyez une notification Windows pour vérifier les alertes du bureau.",
        "Send Test Notification": "Envoyer une notification test",
        "Make LYRx more comfortable to use.": "Rendez LYRx plus confortable à utiliser.",
        "Reduce motion": "Réduire les animations", "Disable animated movement in supported LYRx controls, including Settings toggles.": "Désactivez les animations dans les contrôles LYRx pris en charge, y compris les interrupteurs.",
        "Larger text": "Texte plus grand", "Increase text size across the Settings experience for easier reading.": "Augmentez la taille du texte dans les Paramètres pour faciliter la lecture.",
        "Project information, links and current build details.": "Informations du projet, liens et détails de la version actuelle.",
        "Version": "Version", "Current LYRx desktop portfolio build.": "Version actuelle du portfolio LYRx.",
        "Technology": "Technologie", "Core technologies used by the current build.": "Technologies principales utilisées par cette version.",
        "Project status": "État du projet", "LYRx is an independently developed portfolio project.": "LYRx est un projet portfolio développé indépendamment.",
        "LYRx website": "Site web LYRx", "Open the public LYRx project website.": "Ouvrez le site public du projet LYRx.", "Open Website": "Ouvrir le site",
        "View the public LYRx Privacy Policy.": "Consultez la politique de confidentialité publique de LYRx.",
        "Terms": "Conditions", "Terms of Service": "Conditions d’utilisation", "View the public LYRx Terms of Service.": "Consultez les conditions d’utilisation publiques de LYRx.",
        "←  Settings": "←  Paramètres",
        "Automatic": "Automatique", "Low": "Faible", "Normal": "Normale", "High": "Élevée", "Very High": "Très élevée",
        "Default": "Par défaut", "Female": "Femme", "Male": "Homme", "Non-binary": "Non binaire", "Prefer not to say": "Préfère ne pas répondre",
        "India": "Inde", "United States": "États-Unis", "Canada": "Canada", "United Kingdom": "Royaume-Uni", "Australia": "Australie", "Other": "Autre",
    },
}

LANGUAGE_NAMES = {"en": "English", "hi": "हिन्दी", "fr": "Français"}


class LanguageManager(QObject):
    language_changed = Signal(str)

    def __init__(self):
        super().__init__()
        self.settings = QSettings("LYRx", "LYRxDesktop")
        saved = str(self.settings.value("settings/language_code", "") or "").strip().lower()
        if not saved:
            legacy = str(self.settings.value("settings/language", "English") or "English")
            saved = {"English": "en", "हिन्दी": "hi", "Français": "fr"}.get(legacy, "en")
        self._language = saved if saved in TRANSLATIONS else "en"

    @property
    def language(self):
        return self._language

    def set_language(self, code: str):
        code = str(code or "en").lower()
        if code not in TRANSLATIONS:
            code = "en"
        self.settings.setValue("settings/language_code", code)
        self.settings.setValue("settings/language", LANGUAGE_NAMES[code])
        if code == self._language:
            return
        self._language = code
        self.language_changed.emit(code)

    def translate_literal(self, text: str):
        text = str(text or "")
        if self._language == "en":
            return text
        return LITERAL_TRANSLATIONS.get(self._language, {}).get(text, text)

    def tr(self, key: str, **kwargs):
        text = TRANSLATIONS.get(self._language, {}).get(key)
        if text is None:
            text = TRANSLATIONS["en"].get(key, key)
        try:
            return text.format(**kwargs)
        except (KeyError, ValueError):
            return text


language_manager = LanguageManager()

def tr(key: str, **kwargs):
    return language_manager.tr(key, **kwargs)
